### PR TITLE
Move products to membership price object

### LINKED ISSUE #164: Create monthly and annual products and attach them to the checkout
So that coupons can be used by customers for specific monthly and yearly plans (via the `Coupon.applies_to` field), the checkout flow should:

- [x] Allow promo codes in the checkout
- [ ] Create month/year-specific product line items
  - [ ] Solidarity Monthly
  - [ ] Solidarity Annual
  - [ ] All Books Monthly
  - [ ] All Books Annual
  - [ ] Contemporary Monthly
  - [ ] Contemporary Annual
  - [ ] Classic Monthly
  - [ ] Classic Annual
- [x] Apply products to prices in wagtail

### PR DESCRIPTION
**Pull request by janbaykara**
- Closes #164
- Products are now defined for each price, to allow for monthly or annual-specific coupon deployments. As per the old system, if one product is set, it will be automatically taken to checkout and if more than one product is available for a price, the user will be redirected to the product picker.
Screenshot 2022-05-03 at 22 43 37

### CODE REVIEW

**Comment by janbaykara** [comment]
FYI @melaniepatrick I've configured separate monthly / annual products on the production website now.

What we will need to do is apply the active coupons to these products.

Screenshot 2022-05-03 at 23 23 04

**Comment by melaniepatrick** [comment]
Thanks.
I will do this.
If I apply all coupons to shipping then that solves the issue we had in the
checkout previously yes? So it will apply the discount to shipping also?

**Comment by melaniepatrick** [comment]
shall I create these in test mode and then move them to live after I delete
the live ones? Tonight when we do the switch?

**Comment by janbaykara** [comment]
@melaniepatrick re: shipping, yes, exactly. We need to include shipping in all coupons moving forwards.

Feel free to configure them in test mode so you can test them by literally running through the checkout, this is a sandbox environment that you can use to verify the behaviour of coupons and products and things before taking them live.

However ultimately the changes will need to be made to the live stripe data for the coupons to continue to work from this evening.

**Pull request merged**
